### ISSUE TITLE
Add Travis CI to do unit tests on functions

### ISSUE THREAD

**Issue by erictleung** [erictleung/dada2-hpc-workflow#10]
**TODO**:

- [ ] Check that package builds correctly
- [ ] Install `dada2HPCPipe` package correctly and load successfully
- [ ] Run through code workflow
- [ ] Automate code linting with lintr https://github.com/jimhester/lintr

**Resources**:
- https://docs.travis-ci.com/user/languages/r
- https://blog.rstudio.com/2016/03/09/r-on-travis-ci/

**Draft**:

```yml
language: r
cache: packages
bioc_packages:
  - dada2
  - phyloseq
r_packages:
  - dplyr
```
